name: 提交建议
description: 请告诉我框架的不足之处，让我做得更好！
title: "[建议]："
labels: ["help wanted"]

body:
  - type: markdown
    attributes:
      value: |
        ## [【警告：请务必按照 issue 模板填写，不要抱有侥幸心理，一旦发现 issue 没有按照模板认真填写，一律直接关闭】](https://github.com/getActivity/IssueTemplateGuide)
  - type: textarea
    id: input_id_1
    attributes:
      label: 你觉得框架有什么不足之处？【必答】
      description: 你可以描述框架有什么令你不满意的地方
    validations:
      required: true
  - type: dropdown
    id: input_id_2
    attributes:
      label: issue 是否有人曾提过类似的建议？【必答】
      description: 一旦出现重复提问我将不会再次解答
      multiple: false
      options:
        - 未选择
        - 是
        - 否
    validations:
      required: true
  - type: dropdown
    id: input_id_3
    attributes:
      label: 框架文档是否提及了该问题【必答】
      description: 文档会提供最常见的问题解答，可以先看看是否有自己想要的
      multiple: false
      options:
        - 未选择
        - 是
        - 否
    validations:
      required: true
  - type: dropdown
    id: input_id_4
    attributes:
      label: 是否已经查阅框架文档但还未能解决的【必答】
      description: 如果查阅了文档但还是没有解决的话，可以选择是
      multiple: false
      options:
        - 未选择
        - 是
        - 否
    validations:
      required: true
  - type: textarea
    id: input_id_5
    attributes:
      label: 你觉得该怎么去完善会比较好？【非必答】
      description: 你可以提供一下自己的想法或者做法供作者参考
    validations:
      required: false